name: Build
on: [push, pull_request]
jobs:
  build_duk_ubuntu:
    name: Duk Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt install build-essential make python python-yaml bc git
      - name: Build
        run: |
          make duk
      - name: Test
        run: |
          ./duk dist-files/mandel.js
  build_duk_windows:
    name: Duk VS2019 Enterprise
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          echo FIXME
          cl /?
